// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUGr0ICdCO4DDbZ0SohHz5IWdIIGKn1ts',
    appId: '1:762173640857:web:14ea7f7e17438e081b2808',
    messagingSenderId: '762173640857',
    projectId: 'flutter-transaction-app-12098',
    authDomain: 'flutter-transaction-app-12098.firebaseapp.com',
    storageBucket: 'flutter-transaction-app-12098.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_NE1aht2lsJF3QrO-7v_R4k_bUuQuBD8',
    appId: '1:762173640857:android:c1fd7cd43265d0731b2808',
    messagingSenderId: '762173640857',
    projectId: 'flutter-transaction-app-12098',
    storageBucket: 'flutter-transaction-app-12098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-kIbE2j_Yoc_oEG9UyRrLzBHYDH4Jpq8',
    appId: '1:762173640857:ios:4fdc248e8536e9f61b2808',
    messagingSenderId: '762173640857',
    projectId: 'flutter-transaction-app-12098',
    storageBucket: 'flutter-transaction-app-12098.firebasestorage.app',
    iosBundleId: 'com.example.transactionApp',
  );
}
